//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mock.Areas.Administrator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupMember
    {
        public int StudentId { get; set; }
        public int GroupId { get; set; }
        public System.DateTime JoinAt { get; set; }
        public int MemberNumber { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Student Student { get; set; }
    }
}
