//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mock.Areas.Administrator.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScoreBoard
    {
        public int StudentId { get; set; }
        public int ProjectId { get; set; }
        public int Score { get; set; }
        public System.DateTime SubmitAt { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Student Student { get; set; }
    }
}
